export const getWatermarkHtml = (profileOrRole?: any) => {
  let tier = 'Free';
  if (typeof profileOrRole === 'string') {
    tier = profileOrRole;
  } else if (profileOrRole) {
    tier = profileOrRole.tier || profileOrRole.role || 'Free';
  }
  
  if (tier && tier !== 'Free' && tier !== 'guest') {
    return '';
  }
  return `
    <style>
      .watermark {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-45deg);
        font-size: 80px;
        color: rgba(200, 200, 200, 0.2);
        z-index: 9999;
        pointer-events: none;
        white-space: nowrap;
        user-select: none;
        -webkit-user-select: none;
      }
      @media print {
        .watermark {
          color: rgba(150, 150, 150, 0.15) !important;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
      }
    </style>
    <div class="watermark">Generated by Pemuryadi</div>
  `;
};

export const getSignatureHtml = (profile: any) => {
  if (!profile) return '';
  
  const today = new Date().toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
  
  return `
    <div style="margin-top: 40px; display: flex; justify-content: space-between; text-align: center; font-size: 12px; page-break-inside: avoid;">
        <div style="width: 45%;">
            <p>Mengetahui,</p>
            <p>Kepala Sekolah</p>
            <br><br><br><br>
            <p style="font-weight: bold; text-decoration: underline;">${profile.kepalaSekolah || '................................'}</p>
            <p>${profile.jenisNipKepalaSekolah || 'NIP'}. ${profile.nipKepalaSekolah || '................................'}</p>
        </div>
        <div style="width: 45%;">
            <p>Dibuat pada, ${today}</p>
            <p>Guru Pengampu</p>
            <br><br><br><br>
            <p style="font-weight: bold; text-decoration: underline;">${profile.nama || profile.displayName || '................................'}</p>
            <p>${profile.jenisNipGuru || 'NIP'}. ${profile.nip || '................................'}</p>
        </div>
    </div>
  `;
};
